alias ll='ls -lh'
alias lla='ls -lha'
alias lld='ls -lh | grep "^d"'
alias llda='ls -lha | grep "^d"'
alias cd..='cd ..'
alias cdd='cd ..'
alias cddd='cd ..; cd ..'
alias cdddd='cd ..; cd ..; cd ..'
alias cddddd='cd ..; cd ..; cd ..; cd ..'
alias more='less'
alias f1='fg %1'
alias fg1='fg %1'
alias f2='fg %2'
alias fg2='fg %2'
alias f3='fg %3'
alias fg3='fg %3'
alias f4='fg %4'
alias fg4='fg %4'
alias f5='fg %5'
alias fg5='fg %5'
alias g='grep'
alias gi='grep -i'
alias gr='grep -R'
alias gv='grep -v'
alias gri='grep -Ri'
alias wcl='wc -l'
alias v='vim'
alias ba='vim ~/.bash_aliases && source ~/.bash_aliases'
alias psg='ps -e | grep'
alias cpr='cp -r'
alias cpn='cp -n'
alias cprn='cp -rn'
alias mvn='mv -n'
alias rtks='cat /home/bosco/rtk/rtk.xml | grep '
alias r='rails'
alias rjs='cd app/assets/javascripts'
alias rbb='pushd app/assets/javascripts/backbone'
alias rspec='rspec --color --format doc'
alias be='bundle exec '
alias b='bundle '
alias gsm='gnome-system-monitor'
alias msm='mate-system-monitor'
alias mplayersub='mplayer -subcp utf8 -subfont "TakaoExGothic" -subfont-text-scale 3 -subfont-outline 1'

alias rs='rails server'
alias rc='rails console'
alias fs='foreman start web -p 3000'
alias rrg='rake routes | g'
alias rdm='rake db:migrate'
alias rdr='rake db:rollback'

alias pj='python -mjson.tool'

alias youtube-dl='~/dev/youtube-dl/youtube-dl'

alias webshare='ruby -run -e httpd . -p 5555'

alias x='xmodmap ~/.xmodmap'
alias open='gnome-open'
alias clip='xclip -sel clip < '
alias mp3='~/.mp3.rb'
alias jmplayer='~/.jmplayer.rb'

alias github=hub
alias gs='git status -s'
alias ga='git add'
alias gaa='git add .'
alias gau='git add -u'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gcma='git commit -am'
alias c='git commit -am'
alias gpa='git push origin --all'

alias o=open
